### PR TITLE
Add `protoc_args` attribute to `buf_lint_test` and `buf_breaking_test`

### PR DESCRIPTION
**Pull request by sushain97**
Closes https://github.com/bufbuild/rules_buf/issues/37

### CODE REVIEW

**Comment by sushain97** [comment]
The CLA assistant doesn't provide a button for me to actually accept the CLA...

image

**Comment by srikrsna-buf** [comment]
@sushain97 Can you share the OS and browser (with version info) that you tried this on?

**Comment by srikrsna-buf** [comment]
@sushain97 The commit was made using a different github account @sushain-stripe and the pr was opened by your personal account. That could be the issue

**Comment by sushain97** [comment]
@srikrsna-buf wow, great catch! Thanks. Should be fixed now.

**Review by srikrsna-buf — APPROVED** [review]

**Pull request merged**
